### ISSUE TITLE
Metallic PBR shader requires a metalness texture to have specularity

### ISSUE THREAD

**Issue by nukeandbeans** [Henry00IS/VertexTracer#2]
When creating a PBR material, the expectation is for the shader to provide basic specularity with the smoothness slider, and more advanced specularity with the metalness texture. The current result is that the material has *no* specularity unless the metalness texture is applied.

[Video (ugh GitHub, 10mb is not enough!!)](https://cdn.discordapp.com/attachments/495110443606474763/1066750294865756210/2023-01-22_10-04-15.mp4)

**Comment by Henry00IS** [comment]
The default shader property can be set to the following colors:

**According to this Unity Manual:** https://docs.unity3d.com/Manual/SL-Properties.html
_Put the following values in the default value string to use one of Unity’s built-in textures: “white” (RGBA: 1,1,1,1), “black” (RGBA: 0,0,0,1), “gray” (RGBA: 0.5,0.5,0.5,1), “bump” (RGBA: 0.5,0.5,1,0.5) or “red” (RGBA: 1,0,0,1)._

**According to this Unity Manual:** https://docs.unity3d.com/2019.3/Documentation/Manual/SL-Properties.html
_For 2D Textures, the default value is either an empty string, or one of the built-in default Textures: “white” (RGBA: 1,1,1,1), “black” (RGBA: 0,0,0,0), “gray” (RGBA: 0.5,0.5,0.5,0.5), “bump” (RGBA: 0.5,0.5,1,0.5) or “red” (RGBA: 1,0,0,0)._

**According to my findings:**
The manuals are inconsistent and wrong.
“white” (RGBA: 1,1,1,1).
“black” (RGBA: 0,0,0,0).

The color we need is black (RGBA: 0,0,0,1) but it does not exist.

The result of "black" is a completely flat material:
![Diffuse Example](https://user-images.githubusercontent.com/7905726/218171216-ecc09c3d-621d-48c0-9d3e-9635fc99acd2.png)

The result of "white" is a metallic material that can be tweaked with the smoothness slider.
![Metallic Example](https://user-images.githubusercontent.com/7905726/218171706-b179ee7d-0d61-421e-a301-270d065533fd.png)
